import type { Metadata } from "next";
import { Google_Sans, Zen_Dots } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";

const googleSans = Google_Sans({
  variable: "--font-google-sans",
  subsets: ["latin"],
});

const zenDots = Zen_Dots({
  variable: "--font-zen-dots",
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${googleSans.variable} ${zenDots.variable}`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
